version: "3"
services:
  postgresql:
    container_name: postgresql
    image: bitnami/postgresql:latest
    expose:
      - "5432"
    tty: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  spring_boot:
    container_name: spring_boot
    image: ${SPRING_BOOT_IMAGE}
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./backend:/server

  nginx:
    container_name: nginx_con
    build:
      dockerfile: dockerfile
      context: ./nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - spring_boot


  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/frontend
      - ./frontend/node_modules/:/frontend/node_modules